version: '3'

services:
    db:
        image: postgres:11
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        environment:   
            - POSTGRES_USER=Testuser
            - POSTGRES_PASSWORD=testpassword
            - POSTGRES_DB=mydockerdb
        ports:
            - "5432:5432"

    backend:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    postgres-data:
        driver: local

