# Generated by Django 3.0.4 on 2020-03-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='testvalue',
            field=models.BooleanField(default=True),
        ),
    ]
