# Generated by Django 3.0.4 on 2020-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='huteye',
            name='created_at',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
