# Generated by Django 3.0.4 on 2020-03-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0003_remove_measurement_testvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='timestamp',
            field=models.CharField(default='no timestamp', max_length=55),
        ),
    ]
