# Generated by Django 3.0.4 on 2020-04-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0004_huteye_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huteye',
            name='created_at',
        ),
        migrations.AddField(
            model_name='huteyerecord',
            name='created_at',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
