# Generated by Django 3.0.4 on 2020-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0005_auto_20200406_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huteyerecord',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
